name: PR Code Quality Check

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run linters and type checks
    runs-on: ubuntu-latest
    concurrency:
      group: pr-${{ github.event.pull_request.number }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install black flake8 isort mypy

      - name: Run Black
        id: black
        run: |
          black --check . 2>&1 | tee black_output.txt
        continue-on-error: true

      - name: Run Flake8
        id: flake8
        run: |
          flake8 . 2>&1 | tee flake8_output.txt
        continue-on-error: true

      - name: Run isort
        id: isort
        run: |
          isort --check-only . 2>&1 | tee isort_output.txt
        continue-on-error: true

      - name: Run mypy
        id: mypy
        run: |
          mypy . 2>&1 | tee mypy_output.txt
        continue-on-error: true

      - name: Post Comment on PR if any check fails
        if: always()
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            :warning: **Code quality checks failed!**
            <details>
            <summary>Black Errors</summary>
            ```
            $(cat black_output.txt)
            ```
            </details>
            <details>
            <summary>Flake8 Errors</summary>
            ```
            $(cat flake8_output.txt)
            ```
            </details>
            <details>
            <summary>Isort Errors</summary>
            ```
            $(cat isort_output.txt)
            ```
            </details>
            <details>
            <summary>Mypy Errors</summary>
            ```
            $(cat mypy_output.txt)
            ```
            </details>
            Please fix these issues before merging.
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fail the job if any check fails
        run: |
          grep -q 'error' black_output.txt && exit 1 || true
          grep -q 'error' flake8_output.txt && exit 1 || true
          grep -q 'error' isort_output.txt && exit 1 || true
          grep -q 'error' mypy_output.txt && exit 1 || true